### ISSUE TITLE
[Bug]: Game crashes when running sim at 10kHz or slower but works fine at 100kHz or faster

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#259]
### Discord Thread

https://discord.com/channels/828292123936948244/1289107621265281047

### What happened?

```
fatal.nim(54)            sysFatal
Error: unhandled exception: over- or underflow [OverflowDefect]
```
At 100kHz, the simulation runs for 324k ticks before it hits a Halt component and stops as expected (the end of my program). At 10kHz it sometimes makes it to 324k, but more often it crashes at tick 1.2k. It's always 1.2k; I don't know what's significant about it.

### Version

0.1175 Beta

### What OSes are you seeing the problem on?

Linux

### Relevant `debug.log` output, search next to the exectuable

```shell
#6  0x00007fc88ee32948 in showErrorMessage__system_3071 () from /home/arnavion/.steam/debian-installation/steamapps/common/Turing Complete/libbackend.so
#7  0x00007fc88ee319b3 in reportUnhandledErrorAux__system_3278 () from /home/arnavion/.steam/debian-installation/steamapps/common/Turing Complete/libbackend.so
#8  0x00007fc88ee31b99 in raiseExceptionAux__system_3392 () from /home/arnavion/.steam/debian-installation/steamapps/common/Turing Complete/libbackend.so
#9  0x00007fc88ee320e1 in raiseOverflow () from /home/arnavion/.steam/debian-installation/steamapps/common/Turing Complete/libbackend.so
#10 0x00007fc88efd76d4 in draw_marker.backend_22529.constprop () from /home/arnavion/.steam/debian-installation/steamapps/common/Turing Complete/libbackend.so
#11 0x00007fc88f01752f in update_dynamic_state.backend_6596 () from /home/arnavion/.steam/debian-installation/steamapps/common/Turing Complete/libbackend.so
#12 0x00007fc88f019548 in methFunc__backend_3879 () from /home/arnavion/.steam/debian-installation/steamapps/common/Turing Complete/libbackend.so
#13 0x0000000001efdaa6 in NativeScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) ()
#14 0x0000000000aaa073 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) ()
#15 0x00000000009efbfe in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) ()
#16 0x0000000001e98027 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) ()
#17 0x0000000001e9f8f0 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) ()
```

**Comment by Stuffe** [comment]
fixed
